### ISSUE TITLE
[macOS v0.33]] The application does not start at all

### ISSUE THREAD

**Issue by ddobrev** [eul-im/eul#83] opened 2018-04-21 15:00 UTC
A hint which might help you: trying to launch from the terminal with:

`open -a "eul.app"`

gives:

`LSOpenURLsWithRole() failed for the application /Applications/eul.app with error -10810.`

Trying to directly launch the executable with:

`/Applications/eul.app/Contents/MacOS/eul`

gives:

`dyld: Library not loaded: libnanovg.a
  Referenced from: /Applications/eul.app/Contents/MacOS/eul
  Reason: image not found
Abort trap: 6`

**Comment by jgbrwn** [comment] 2018-04-21 17:39
Same.  High Sierra / 10.13.4.

Non-cli/regular startup yields:

![image](https://user-images.githubusercontent.com/11037782/39087083-3d1869f8-4569-11e8-9c63-1c274ecb91a4.png)

**Comment by ddobrev** [comment] 2018-04-22 08:57
My macOS is 10.13.4 as well.

**Comment by tuananh** [comment] 2018-04-22 11:05
Too bad, this app has so much potential. Just getting a little more polish.

**Comment by tuananh** [comment] 2018-04-24 01:43
still not working on v0.34. I'm giving up.

**Comment by jamesgecko** [comment] 2018-04-24 20:07
I don't even see a crash message; nothing happens and then the `ReportCrash` process opens in the background and slowly grows to consume all my CPU cycles.

**Comment by zsszatmari** [comment] 2018-04-25 19:29
Same here. :'(

**Comment by ddobrev** [comment] 2018-04-25 19:41
I also get the same - including the detailed errors I've posted - with 0.34.

**Comment by claui** [comment] 2018-04-25 22:36
I’ve written a [Homebrew formula](https://gist.github.com/claui/a950e08517ff7cbe060966a4d5f87f4a) for `libnanovg`, which seems to work around this problem for me. It may be of use for those who don’t want to wait until a new version of eul is released that fixes the issue.

Please bear in mind that this is not an official Homebrew formula (yet). It’s still under test, and may not work on your computer. **Do not install this formula unless you have a good backup.**

**To install the formula,** follow these steps:

1. Make sure you have [Homebrew](https://brew.sh/) installed.

2. Download the [libnanovg.rb](https://gist.github.com/claui/a950e08517ff7cbe060966a4d5f87f4a) formula.

3. Open Terminal.app.

4. `cd` to the folder which contains the `libnanovg.rb` formula.

5. Run `brew install --HEAD libnanovg.rb`. This will install two libraries to `/usr/local/lib`: `libnanovg.a` and `libnanovg.dylib`.

6. Two manual tweaks are needed to fix the eul issue (the Mac version of eul appears to mix up the extensions). First, delete the `/usr/local/lib/libnanovg.a` symlink.

7. Finally, rename the remaining symlink `/usr/local/lib/libnanovg.dylib` to `/usr/local/lib/libnanovg.a`.

This should work around the issue, and will also survive updates of eul. You can uninstall the formula as soon as the issue is fixed in eul.

**To uninstall the formula,** run:

```
brew uninstall libnanovg
```

If you have any questions or comments regarding the formula, be sure to post them [in the formula Gist](https://gist.github.com/claui/a950e08517ff7cbe060966a4d5f87f4a), not here.

**Comment by stevenleeg** [comment] 2018-04-26 14:13
Running into the same issue here, app immediately crashes upon opening (or shows the "cannot be opened" alert).

**Comment by ddobrev** [comment] 2018-05-01 09:36
I get an error with the formula:

```
==> Cloning https://github.com/memononen/nanovg.git
Updating /Users/ddobrev/Library/Caches/Homebrew/libnanovg--git
==> Checking out branch master
==> Patching
patching file premake4.lua
Hunk #1 FAILED at 3.
Hunk #2 FAILED at 14.
2 out of 2 hunks FAILED -- saving rejects to file premake4.lua.rej
Error: Failure while executing: patch -g 0 -f -p1
```

Anyway, it's such a shame. A native client for Slack is desperately needed and this one cannot even get its dependencies right, not to mention the yet another missed own deadline of April the 30th.

**Comment by claui** [comment] 2018-05-01 09:37
Thanks @ddobrev for the feedback. I’m looking into it.

**Comment by claui** [comment] 2018-05-01 10:42
@ddobrev Please create a Gist with both `premake4.lua.orig` and `premake4.lua.rej`, which have been generated by the failed install, and comment [here](https://gist.github.com/claui/a950e08517ff7cbe060966a4d5f87f4a) with the link to your Gist.

**Comment by ddobrev** [comment] 2018-05-01 10:53
@claui I would be happy to help but I cannot find these files even though one of them is mentioned in the output. Would you know where I need to look?

**Comment by claui** [comment] 2018-05-01 15:13
@ddobrev I’ve [replied to you in the Gist](https://gist.github.com/claui/a950e08517ff7cbe060966a4d5f87f4a#gistcomment-2575801) so as to keep this issue focused on getting eul fixed.

**Comment by ddobrev** [comment] 2018-05-03 09:40
Absolutely the same with 0.35. Does anybody read these reports at all?
@claui I am afraid I could not find these files but don't worry about me. The application is obviously still way too unreliable so I would not use it even if your patch had worked on my machine.

**Comment by jessb321** [comment] 2018-05-03 11:13
I noticed that the .app in the zip hasn't been modified since the 16th of April.

**Comment by ddobrev** [comment] 2018-05-04 19:31
This is ridiculous. The copy from "brew cask install eul" has the exact same behaviour. Basically, all the development I can see in the last month is constantly changing and missed deadlines. At least open the source code so that we can fix problems ourselves.

**Comment by jamesgecko** [comment] 2018-05-04 22:08
It is what it is. We didn’t pay any money; we aren’t owed a schedule or source code. If it’s unusable, don’t use it.

Edit: unless you’re a patreon, maybe? But even then you’re basically buying development time, not software.

**Comment by nitinja** [comment] 2018-05-08 00:05
Eul looks incredible, too bad it doesn't work as of now.

**Comment by nikolay** [comment] 2018-05-09 23:59
@claui You can actually install in a single step like this:

```Bash
brew install --HEAD https://gist.githubusercontent.com/claui/a950e08517ff7cbe060966a4d5f87f4a/raw/e5f2de29c52c2c584e9efc01e72126011024c9c9/libnanovg.rb
```

**Comment by voltapp2** [comment] 2019-02-08 14:41
Nanovg is no longer used, so this won't be a problem any more.

I did a terrible job with the development in 2018. Lots of bad decisions and lack of communication.

Sorry about that.

Soon I'll post a detailed blog about what caused the 9 month delay.

The macOS version was revived a couple of days ago: https://volt.ws/mac

**Closed as completed by voltapp2** 2019-02-08 14:41 UTC
