### ISSUE TITLE
Windows 7: Repeated "initial setup" message

### ISSUE THREAD

**Issue by weebs** [eul-im/eul#144] opened 2019-04-01 13:35 UTC
The "Volt for Windows temporarily has to be restarted after intial setup. Please restart the app." is continuously showing for me on Windows 7 with the official download link as of 4/1/2019

My computer has a policy that does not allow arbitrary executables to be run from AppData put in place by IT, so this may be interfering with the apps bootstrap process? I'm not sure what it's doing during initial setup

**Comment by spoltier** [comment] 2019-04-02 08:45
I think this is a duplicate of https://github.com/voltapp/volt/issues/132

**Comment by weebs** [comment] 2019-04-07 18:23
Correct, closing this.

**Closed as completed** 2019-04-07 18:23 UTC
